ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER eml_app IDENTIFIED BY "Em1App123"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA 100M ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO eml_app;
ALTER USER eml_app QUOTA UNLIMITED ON USERS;
