CREATE TABLE users (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username VARCHAR2(100) NOT NULL UNIQUE,
  email VARCHAR2(255) NOT NULL UNIQUE,
  password_hash VARCHAR2(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE email_scans (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  filename VARCHAR2(255) NOT NULL,
  verdict VARCHAR2(50) NOT NULL,
  risk_score NUMBER(3) NOT NULL,
  threat_level VARCHAR2(20) NOT NULL,
  scanned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_email_scans_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE threat_indicators (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  scan_id NUMBER NOT NULL,
  indicator_type VARCHAR2(100) NOT NULL,
  indicator_value VARCHAR2(500) NOT NULL,
  CONSTRAINT fk_threat_indicators_scan FOREIGN KEY (scan_id) REFERENCES email_scans(id)
);
